version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bigbasket-ecommerce
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/bigbasket
    
  db:
    image: mongo:6-jammy
    container_name: bigbasket-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: